sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8å
    - clang

before_script:
  - g++ --version

script:
  - make build
  - make test
