sudo: required

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++-5

before_script:
  - g++ --version

script:
  - make build
  - make test
